name: marconi_app
description: Application for the ITI Marconi Verona.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  http: ^0.12.1
  dio: ^3.0.9
  connectivity: ^0.4.8+6
  freezed_annotation: ^0.7.1
  dartz: ^0.9.1
  kt_dart: ^0.7.0+1
  flutter_secure_storage: ^3.3.3
  dio_http_cache: ^0.2.6
  intl: ^0.16.1
  moor_flutter: ^3.0.0
  injectable: ^0.3.0
  get_it: ^4.0.2
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.9.0
  smooth_page_indicator: ^0.1.5
  equatable: ^1.1.1
  table_calendar: ^2.2.3
  flutter_linkify: ^3.1.3
  url_launcher: ^5.4.7
  percent_indicator: ^2.1.1
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  lint: ^1.2.0
  build_runner:
  freezed: ^0.10.8
  json_serializable: ^3.3.0
  moor_generator: ^3.0.0
  injectable_generator: ^0.3.5
  auto_route_generator: ^0.3.2

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/logo/logo_app_android.png"
  image_path_ios: "assets/logo/logo_app_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/splash_screen_logo/
    - assets/logo/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
